language: cpp
compiler: gcc
dist: xenial

cache:
  directories:
  - $HOME/.cache

env:
- SETUP_PATH=.ci-local:.ci

addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - qemu-system-x86

install:
  - ./.ci/travis-prepare.sh

script:
  - ./.ci/travis-build.sh

matrix:
  include:

# Different configurations of default gcc and clang

  - env: BASE=R7.0.1

  - env: BASE=R7.0.3
    compiler: clang

  - env: BASE=7.0 EXTRA="CMD_CXXFLAGS=-std=c++11"

  - env: BASE=7.0 EXTRA="CMD_CXXFLAGS=-std=c++11"
    compiler: clang

# MacOS build

  - env: BASE=7.0
    os: osx
    compiler: clang
